/*
 * Copyright (c) 2018 RSBuddy Ltd. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *    * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *    * Neither the name of RSBuddy Ltd. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.rsbuddy.osrs.content.config;

public interface AnimationId {

    int IDLE = -1;

    int BREAK_INFERNAL_EEL = 7553;

    int CHISEL_SAPPHIRE = 888;
    int CHISEL_EMERALD = 889;
    int CHISEL_RUBY = 887;
    int CHISEL_DIAMOND = 886;
    int CHISEL_DRAGONSTONE = 885;
    int CHISEL_ONYX = 2717;

    int COOKING_FIRE = 897;
    int COOKING_RANGE = 896;

    int CRAFTING_GLASSBLOWING = 884;
    int CRAFTING_MAKE_STAFF = 7531;
    int CRAFTING_SPINNING = 894;
    int CRAFTING_LEATHER = 1249;

    int FIREMAKING_LIGHT_LOG = 733;

    int FISHING_BARBARIAN = 6709;
    int FISHING_BIG_NET = 620;
    int FISHING_SMALL_NET = 621;
    int FISHING_NORMAL_ROD = 623;
    int FISHING_OILY_ROD = 622;
    int FISHING_CAGE = 619;
    int FISHING_NORMAL_HARPOON = 618;
    int FISHING_BARBTAIL_HARPOON = 5108;
    int FISHING_DRAGON_HARPOON = 7401;
    int FISHING_INFERNAL_HARPOON = 7402;
    int FISHING_KARAMBWAN = 1193;

    int FLETCHING_CUT_LOG = 1248;
    int FLETCHING_STRING_NORMAL_SHORTBOW = 6678;
    int FLETCHING_STRING_OAK_SHORTBOW = 6679;
    int FLETCHING_STRING_WILLOW_SHORTBOW = 6680;
    int FLETCHING_STRING_MAPLE_SHORTBOW = 6681;
    int FLETCHING_STRING_YEW_SHORTBOW = 6682;
    int FLETCHING_STRING_MAGIC_SHORTBOW = 6683;
    int FLETCHING_STRING_NORMAL_LONGBOW = 6684;
    int FLETCHING_STRING_OAK_LONGBOW = 6685;
    int FLETCHING_STRING_WILLOW_LONGBOW = 6686;
    int FLETCHING_STRING_MAPLE_LONGBOW = 6687;
    int FLETCHING_STRING_YEW_LONGBOW = 6688;
    int FLETCHING_STRING_MAGIC_LONGBOW = 6689;

    // pestle and mortar
    int GRIND = 364;

    int HERBLORE_GRIND_TAR = 5249;
    int HERBLORE_MIX_POTION = 363;

    int FARMING_ULTRA_COMPOST = 7699;

    int MINING_NORMAL_BRONZE = 625;
    int MINING_NORMAL_IRON = 626;
    int MINING_NORMAL_STEEL = 627;
    int MINING_NORMAL_BLACK = 3873;
    int MINING_NORMAL_MITHRIL = 629;
    int MINING_NORMAL_ADAMANT = 628;
    int MINING_NORMAL_RUNE = 624;
    int MINING_NORMAL_DRAGON = 7139;
    int MINING_NORMAL_DRAGON_ORN = 642;
    int MINING_NORMAL_INFERNAL = 4482;
    int MINING_NORMAL_3A = 7283;

    int MINING_MOTHERLODE_BRONZE = 6753;
    int MINING_MOTHERLODE_IRON = 6754;
    int MINING_MOTHERLODE_STEEL = 6755;
    int MINING_MOTHERLODE_BLACK = 3866;
    int MINING_MOTHERLODE_MITHRIL = 6757;
    int MINING_MOTHERLODE_ADAMANT = 6756;
    int MINING_MOTHERLODE_RUNE = 6752;
    int MINING_MOTHERLODE_DRAGON = 6758;
    int MINING_MOTHERLODE_DRAGON_ORN = 335;
    int MINING_MOTHERLODE_INFERNAL = 4481;
    int MINING_MOTHERLODE_3A = 7282;

    int SMITHING_SMELTING = 899;
    int SMITHING_CANNONBALL = 827;

    int WOODCUTTING_BRONZE = 879;
    int WOODCUTTING_IRON = 877;
    int WOODCUTTING_STEEL = 875;
    int WOODCUTTING_BLACK = 873;
    int WOODCUTTING_MITHRIL = 871;
    int WOODCUTTING_ADAMANT = 869;
    int WOODCUTTING_RUNE = 867;
    int WOODCUTTING_DRAGON = 2846;
    int WOODCUTTING_INFERNAL = 2117;
    int WOODCUTTING_3A = 7264;

}
